### ISSUE TITLE
внедрить поддержку аутентификации для url камер

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/Z-Way-Android#17]
в формате http://user:passwd@domain/uri

**Comment by PoltoS** [comment]
Проблему решили на стороне сервера - теперь по урлу возвращается проксированный сервером поток с камеры. Требуется изменение: если пришёл урл вида /xxxx, то подставлять http://IP:PORT к этому урлу. Если же путь абсолютный с именем сервера, то использовать как есть.

Проверить можно на коробке 10185 - камера 28

**Comment by IvanPl311** [comment]
Сергей, привет.
Понял, спасибо. Моленько выпал из процесса:( Накрылся комп, только сегодня
удалось все восстановить

30 сентября 2014 г., 5:19 пользователь Poltorak Serguei <
notifications@github.com> написал:

> Проблему решили на стороне сервера - теперь по урлу возвращается
> проксированный сервером поток с камеры. Требуется изменение: если пришёл
> урл вида /xxxx, то подставлять http://IP:PORT к этому урлу. Если же путь
> абсолютный с именем сервера, то использовать как есть.
> 
> Проверить можно на коробке 10185 - камера 28
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Z-Wave-Me/Z-Way-Android/issues/17#issuecomment-57239586
> .

## 

С уважением,
Иван

**Comment by IvanPl311** [comment]
Сергей привет

Требуется изменение: если пришёл урл вида /xxxx, то подставлять

> http://IP:PORT к этому урлу.

A если мы коннектимся через find.z-wave.me, как тогда?
И можно одну из камер сделать с абсолютный с именем сервера?

30 сентября 2014 г., 5:19 пользователь Poltorak Serguei <
notifications@github.com> написал:

> Проблему решили на стороне сервера - теперь по урлу возвращается
> проксированный сервером поток с камеры. Требуется изменение: если пришёл
> урл вида /xxxx, то подставлять http://IP:PORT к этому урлу. Если же путь
> абсолютный с именем сервера, то использовать как есть.
> 
> Проверить можно на коробке 10185 - камера 28
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Z-Wave-Me/Z-Way-Android/issues/17#issuecomment-57239586
> .

## 

С уважением,
Иван

**Comment by IvanPl311** [comment]
А еще пришел в crittercism OutOfMemoryError при попытке получить с сервака
нотификашки. я боюсь представить сколько их там было. С нотификашками
вообще странные вещи творятся, но тут мне наверное нужно поговорить со
Стасом. У нас каждый раз приходят все нотификашки заново почему то.

1 октября 2014 г., 21:58 пользователь Ivan Platonov ivanpl311@gmail.com
написал:

> Сергей привет
> 
> Требуется изменение: если пришёл урл вида /xxxx, то подставлять
> 
> > http://IP:PORT к этому урлу.
> 
> A если мы коннектимся через find.z-wave.me, как тогда?
> И можно одну из камер сделать с абсолютный с именем сервера?
> 
> 30 сентября 2014 г., 5:19 пользователь Poltorak Serguei <
> notifications@github.com> написал:
> 
> > Проблему решили на стороне сервера - теперь по урлу возвращается
> > проксированный сервером поток с камеры. Требуется изменение: если пришёл
> > урл вида /xxxx, то подставлять http://IP:PORT к этому урлу. Если же путь
> > абсолютный с именем сервера, то использовать как есть.
> > 
> > Проверить можно на коробке 10185 - камера 28
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Z-Wave-Me/Z-Way-Android/issues/17#issuecomment-57239586
> > .
> 
> ## 
> 
> С уважением,
> Иван

## 

С уважением,
Иван

**Comment by PoltoS** [comment]
так добавлять же надо сервер и порт самого сервака, т.е. в случае find это будет сам find. Он камеру и проксирует.

**Comment by IvanPl311** [comment]
Конечно, первые 15 уже пришли:)
Я пробовал подставлять сам find но чет ничего не работает, кажись потому
что я куки не посылал...

1 октября 2014 г., 23:50 пользователь Poltorak Serguei <
notifications@github.com> написал:

> так добавлять же надо сервер и порт самого сервака, т.е. в случае find это
> будет сам find. Он камеру и проксирует.
> 
> тебе Стас денег, кстати, отправил. там 15, т.к. в день ограничнение. он за
> 4 дня 60 перебросит и остальное чуть позже. ок?
> 
> ----- Исходное сообщение -----
> 
> > От: "Ivan Platonov" notifications@github.com
> > Кому: "Z-Wave-Me/Z-Way-Android" Z-Way-Android@noreply.github.com
> > Копия: "Poltorak Serguei" poltorak@alsenet.com
> > Отправленные: Среда, 1 Октябрь 2014 г 18:58:12
> > Тема: Re: [Z-Way-Android] внедрить поддержку аутентификации для url камер
> > (#17)
> > 
> > Сергей привет
> > 
> > Требуется изменение: если пришёл урл вида /xxxx, то подставлять
> > 
> > > http://IP:PORT к этому урлу.
> > 
> > A если мы коннектимся через find.z-wave.me, как тогда?
> > И можно одну из камер сделать с абсолютный с именем сервера?
> > 
> > 30 сентября 2014 г., 5:19 пользователь Poltorak Serguei <
> > notifications@github.com> написал:
> > 
> > > Проблему решили на стороне сервера - теперь по урлу возвращается
> > > проксированный сервером поток с камеры. Требуется изменение: если
> > > пришёл
> > > урл вида /xxxx, то подставлять http://IP:PORT к этому урлу. Если же
> > > путь
> > > абсолютный с именем сервера, то использовать как есть.
> > > 
> > > Проверить можно на коробке 10185 - камера 28
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/Z-Wave-Me/Z-Way-Android/issues/17#issuecomment-57239586
> > > 
> > > .
> > 
> > ## 
> > 
> > С уважением,
> > Иван
> > 
> > —
> > Reply to this email directly or view it on GitHub .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Z-Wave-Me/Z-Way-Android/issues/17#issuecomment-57497645
> .

## 

С уважением,
Иван
