### ISSUE TITLE
Не срабатывает включени реле horstmann

### ISSUE THREAD

**Issue by chorus12** [Z-Wave-Me/Z-Way-Android#44]
Добрый день!
Из приложения android (на планшете sony) ~ в 30% случаев не срабатывает включение реле hotsmann. Приложение показывает, что реле включилось, но в действительности это не так.

**Comment by PoltoS** [comment]
log?

**Comment by chorus12** [comment]
Сегодня увидел такую же ситуацию с доступом с обычного компьютера. Воспроизвести просто - надо зайти на сервис find.z-wave.me и оставить окошко с виджетами без активности минут на 10-15. После этого можно дёргать любые выключатели - на конечных устройствах это не будет отражаться. Видмо, что-то по таймауту отваливается.
